services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ".env.prod"
    ports:
      - "8000:443"  # Redirige le port 8000 externe vers le port 443 interne (HTTPS)
      #- "80:80"     # Laissez cette ligne si vous voulez aussi HTTP standard
    #Décommenter les 2 lignes ci-dessous pour mode dev et lier les fichiers locaux de ceux du container
    #volumes:
    #  - .:/var/www/html
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: M0tDePasseB!donIlFautLeChanger
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    ports:
      - "8081:80"
    depends_on:
      - db

  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

volumes:
  mysql_data:
  mongo_data: