version: '3.6'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: 'ePStl]LoOamt8dZ2'
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  symfony:
    build: .
    container_name: ecoride_symfony
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://ecoride:ePStl]LoOamt8dZ2@db:3306/ecoride" # Utilisation de "db" pour le réseau Docker
      COMPOSER_MEMORY_LIMIT: -1
    depends_on:
      - db

volumes:
  db_data:

