version: '3.6'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride
      MYSQL_PASSWORD: 'ePStl]LoOamt8dZ2'
    ports:
      - "3307:3306" # Change le port exposé à 3307 pour éviter le conflit avec la machine locale
    volumes:
      - db_data:/var/lib/mysql

  symfony:
    build: .
    container_name: ecoride_symfony
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql://ecoride:ePStl]LoOamt8dZ2@db:3306/ecoride"
    depends_on:
      - db

volumes:
  db_data:
