# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    timezone: '%env(APP_TIMEZONE)%'
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    # Configuration PHPMailer
    smtp_host: '%env(SMTP_HOST)%'
    smtp_port: '%env(int:SMTP_PORT)%'
    smtp_username: '%env(SMTP_USERNAME)%'
    smtp_password: '%env(SMTP_PASSWORD)%'
    smtp_sender_email: '%env(SMTP_SENDER_EMAIL)%'
    smtp_sender_name: '%env(SMTP_SENDER_NAME)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Service\MongoService:
        arguments:
            $documentManager: '@doctrine_mongodb.odm.document_manager'

    App\Service\AddressValidator:
        arguments:
            $httpClient: '@http_client'

    App\Service\MailService:
        arguments:
            $mailsTypeRepository: '@App\Repository\MailsTypeRepository'
            $smtpHost: '%smtp_host%'
            $smtpPort: '%smtp_port%'
            $smtpUsername: '%smtp_username%'
            $smtpPassword: '%smtp_password%'
            $smtpSenderEmail: '%smtp_sender_email%'
            $smtpSenderName: '%smtp_sender_name%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Service/MailService.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
